services:
  tracer-customer-portal-frontend:
    image: 857264224373.dkr.ecr.eu-north-1.amazonaws.com/tracer/customer-portal-frontend:24
    ports:
      - "8081:8080"
    networks:
      - app-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first

networks:
  app-network:
    driver: overlay
    attachable: true  # Allows manual attachment to the network
