services:
  tracer-customer-portal-frontend:
    image: nginx:latest
    networks:
      - app-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    ports:
      - "80:80"  # Expose port 8080 inside the container and map it to port 8081 on the host for external access

networks:
  app-network:
    driver: overlay
    attachable: true  # Allows manual attachment to the network
